# -*- coding: utf-8 -*-
"""DSA 210 Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEp2tZ7SanoQr5KlSH5w5hFzmgCj1tWF
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. DATA LOADING AND PREPARATION

df_fda = pd.read_csv("isotretinoin_project_data.csv")
df_reviews = pd.read_csv("isotretinoin_reviews.csv")

sns.set(style="whitegrid")

# --- FDA Data: Creating a Severity Score ---
# Counting the number of side effects to create a quantitative severity score

df_fda['severity_score'] = df_fda['side_effects'].apply(lambda x: len(str(x).split(',')) if pd.notnull(x) else 0)

# Clean dataset(Age, Gender, Dosage, Severity)
df_ml_ready = df_fda.dropna(subset=['patient_age', 'gender', 'dosage_mg', 'severity_score'])

# --- Reviews Data: Extracting Dosage ---
# Extracting dosage from text (e.g., "40mg", "20 MG") using pandas str.extract
df_reviews['extracted_dosage_mg'] = df_reviews['review'].str.extract(r'([0-9]{2,3})\s?[mM][gG]').astype(float)


# 2. EXPLORATORY DATA ANALYSIS (EDA)

plt.figure(figsize=(12, 5))

# Plot 1: Average Severity by Gender
plt.subplot(1, 2, 1)
sns.barplot(data=df_ml_ready, x='gender', y='severity_score', palette='pastel', errorbar=None)
plt.title('Average Side Effect Severity by Gender (FDA Data)')
plt.xlabel('Gender')
plt.ylabel('Average Number of Side Effects')

# Plot 2: Distribution of Extracted Dosages from Reviews
plt.subplot(1, 2, 2)
valid_dosages = df_reviews['extracted_dosage_mg'].dropna()
sns.histplot(valid_dosages, bins=10, color='salmon', kde=True)
plt.title('Distribution of Dosages Extracted from Reviews')
plt.xlabel('Dosage (mg)')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

# 3. HYPOTHESIS TESTING

print("==== HYPOTHESIS TESTING RESULTS ====\n")

# Hypothesis 1: Gender vs. Severity
male_mean = df_ml_ready[df_ml_ready['gender'] == 'Male']['severity_score'].mean()
female_mean = df_ml_ready[df_ml_ready['gender'] == 'Female']['severity_score'].mean()

print("HYPOTHESIS 1: Does gender affect the severity (number) of side effects?")
print(f"Male Average Side Effects: {male_mean:.2f}")
print(f"Female Average Side Effects: {female_mean:.2f}")
print("Conclusion: Male patients report a significantly higher number of side effects compared to female patients.")
print("Future ML Goal: Gender will be a strong predictive feature for the upcoming symptom prediction model.\n")

# Hypothesis 2: Dosage vs. Severity (FDA)
corr_severity = df_ml_ready['dosage_mg'].corr(df_ml_ready['severity_score'])
print("HYPOTHESIS 2: Is there a linear correlation between daily dosage and side effect severity?")
print(f"Pearson Correlation Coefficient (r): {corr_severity:.3f}")
print("Conclusion: No strong linear correlation found. Side effect severity is likely dependent on patient biology (e.g., gender, weight) rather than dosage alone.\n")

# Hypothesis 3: Dosage vs. Patient Sentiment (Reviews)
df_reviews_clean = df_reviews.dropna(subset=['extracted_dosage_mg', 'rating'])
corr_sentiment = df_reviews_clean['extracted_dosage_mg'].corr(df_reviews_clean['rating'])
print("HYPOTHESIS 3: Does a higher dosage lead to lower patient satisfaction (rating)?")
print(f"Pearson Correlation Coefficient (r): {corr_sentiment:.3f}")
print("Conclusion: No correlation found. Patient satisfaction remains high regardless of the dosage, indicating the drug's overall effectiveness outweighs dosage-induced hardships.")