# -*- coding: utf-8 -*-
"""Machine Learning - Model 1 Balanced

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POCFX2O1Wl8CQR8V8qPI72sw-cWqcH0j
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

print("--- MODEL 1: FDA Data (Balanced Risk Classification) ---")

# 1. Load and prepare the data
df_fda = pd.read_csv("isotretinoin_project_data.csv")
df_fda['severity_score'] = df_fda['side_effects'].apply(lambda x: len(str(x).split(',')) if pd.notnull(x) else 0)
df_fda_ml = df_fda.dropna(subset=['patient_age', 'gender', 'dosage_mg', 'severity_score']).copy()

# 2. Classification logic (2 or more side effects = High Risk)
df_fda_ml['risk_level'] = df_fda_ml['severity_score'].apply(lambda x: 1 if x >= 2 else 0)
df_fda_ml['gender_encoded'] = df_fda_ml['gender'].map({'Male': 1, 'Female': 0})

X_fda = df_fda_ml[['patient_age', 'gender_encoded', 'dosage_mg']]
y_fda = df_fda_ml['risk_level']

X_train_fda, X_test_fda, y_train_fda, y_test_fda = train_test_split(X_fda, y_fda, test_size=0.2, random_state=42)

# 3. Train the model (class_weight='balanced' added)
clf_fda_balanced = RandomForestClassifier(n_estimators=100, max_depth=3, class_weight='balanced', random_state=42)
clf_fda_balanced.fit(X_train_fda, y_train_fda)
preds_fda_balanced = clf_fda_balanced.predict(X_test_fda)

# 4. Print the results
acc_fda_balanced = accuracy_score(y_test_fda, preds_fda_balanced)
print(f"Training size: {len(X_train_fda)} | Test size: {len(X_test_fda)}")
print(f"Accuracy Score: {acc_fda_balanced:.2%}")
print("\nClassification Report (Balanced):")
print(classification_report(y_test_fda, preds_fda_balanced, target_names=['Low Risk', 'High Risk'], zero_division=0))

# 5. Feature Importance Visualization
feature_importances = clf_fda_balanced.feature_importances_
feature_names = ['Patient Age', 'Gender (Male=1)', 'Daily Dosage (mg)']

plt.figure(figsize=(8, 5))
sns.barplot(x=feature_importances, y=feature_names, hue=feature_names, palette='magma', legend=False)
plt.title('Feature Importance: Predicting Risk Level (Balanced Model)')
plt.xlabel('Importance Score')
plt.ylabel('Features')
plt.tight_layout()
plt.show()