# -*- coding: utf-8 -*-
"""Machine Learning - Model 1 Standard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POCFX2O1Wl8CQR8V8qPI72sw-cWqcH0j
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

print("--- MODEL 1: FDA Data (Standard Risk Classification) ---")

# 1. Load and prepare the data
df_fda = pd.read_csv("isotretinoin_project_data.csv")
df_fda['severity_score'] = df_fda['side_effects'].apply(lambda x: len(str(x).split(',')) if pd.notnull(x) else 0)
df_fda_ml = df_fda.dropna(subset=['patient_age', 'gender', 'dosage_mg', 'severity_score']).copy()

# 2. Classification logic (2 or more side effects = High Risk)
df_fda_ml['risk_level'] = df_fda_ml['severity_score'].apply(lambda x: 1 if x >= 2 else 0)
df_fda_ml['gender_encoded'] = df_fda_ml['gender'].map({'Male': 1, 'Female': 0})

X_fda = df_fda_ml[['patient_age', 'gender_encoded', 'dosage_mg']]
y_fda = df_fda_ml['risk_level']

X_train_fda, X_test_fda, y_train_fda, y_test_fda = train_test_split(X_fda, y_fda, test_size=0.2, random_state=42)

# 3. Train the model (No class_weight applied)
clf_fda_standard = RandomForestClassifier(n_estimators=100, max_depth=3, random_state=42)
clf_fda_standard.fit(X_train_fda, y_train_fda)
preds_fda_standard = clf_fda_standard.predict(X_test_fda)

# 4. Print the results
acc_fda_standard = accuracy_score(y_test_fda, preds_fda_standard)
print(f"Training size: {len(X_train_fda)} | Test size: {len(X_test_fda)}")
print(f"Accuracy Score: {acc_fda_standard:.2%}")
print("\nClassification Report (Standard):")
print(classification_report(y_test_fda, preds_fda_standard, target_names=['Low Risk', 'High Risk'], zero_division=0))